#!/bin/bash -x
MACHINE=${MACHINE:-ucm-imx8m-mini}
DISTRO=${DISTRO:-fsl-imx-xwayland}
EULA=1

cp -f ../sources/meta-marlin/poky/meta/classes/mime-xdg.bbclass ../sources/poky/meta/classes/mime-xdg.bbclass

. fsl-setup-release.sh $@

declare -a ENVIRONMENT=('../sources/meta-marlin/tools/setup-marlin-env \
		../sources/meta-marlin/tools/setup-user-env')

for env in ${ENVIRONMENT[@]};do
[ -f ${env} ] && FORCE=Yes source ${env}
done
